// What a platform has to provide, and nothing else.
//
// The split that makes this work is between backends that know what a
// button means and backends that do not. macOS's GameController and
// Windows' XInput hand over a controller: this is the South button, this
// is the left trigger. Linux's evdev and macOS's raw HID hand over a
// numbered lump of switches and potentiometers, and the mapping database
// is what turns one into the other. Both kinds implement this interface;
// the core deals with the difference, so a backend never has to.

#ifndef GPPLUS_BACKEND_HPP
#define GPPLUS_BACKEND_HPP

#include <cstdint>
#include <string>

#include <gpplus/gamepad.hpp>

namespace gpp::detail {

struct DeviceDesc {
  std::string name;
  Guid guid;
  std::uint16_t vendor = 0;
  std::uint16_t product = 0;
  std::uint16_t version = 0;
  /// True when this backend reports Buttons and Axes directly and the
  /// database is not consulted for it.
  bool backend_mapped = false;
  int raw_button_count = 0;
  int raw_axis_count = 0;
  int raw_hat_count = 0;
  Capabilities caps;
  /// The backend's own pointer for this device, handed back to it on
  /// rumble() and friends. The core never dereferences it.
  void *handle = nullptr;
  /// Distinguishes two identical pads so the raw backends can tell which
  /// one a mapped backend already claimed. A device path, a registry id,
  /// a serial -- anything stable for as long as it stays plugged in.
  std::string unique_key;
};

/// The core, as a backend sees it. Every call is safe with a slot that has
/// been removed; a backend that reports state for a device the user just
/// unplugged is normal, not a bug.
class Host {
public:
  virtual ~Host() = default;

  /// Returns a slot the backend keeps, or -1 if the core declined the
  /// device -- which happens when a higher-priority backend already owns
  /// the same physical hardware.
  virtual int add_device(const DeviceDesc &desc) = 0;
  virtual void remove_device(int slot) = 0;

  /// Raw backends. Indices past what the device declared are dropped.
  virtual void set_raw_button(int slot, int index, bool down) = 0;
  virtual void set_raw_axis(int slot, int index, float value) = 0;
  virtual void set_raw_hat(int slot, int index, std::uint8_t mask) = 0;

  /// Mapped backends.
  virtual void set_button(int slot, Button b, bool down) = 0;
  virtual void set_axis(int slot, Axis a, float value) = 0;

  virtual void set_power(int slot, PowerLevel level) = 0;

  /// The public id the core gave this slot, for a backend that has to hand
  /// it back out -- the virtual one does, so a test can address the device
  /// it just created.
  [[nodiscard]] virtual DeviceId device_id_for_slot(int slot) const = 0;

  /// Whether a mapped backend has already claimed this hardware. A raw
  /// backend asks before adding, so that a pad macOS understands is not
  /// also reported as a nameless HID blob.
  [[nodiscard]] virtual bool
  hardware_claimed(std::uint16_t vendor, std::uint16_t product,
                   const std::string &unique_key) const = 0;
};

class Backend {
public:
  virtual ~Backend() = default;

  [[nodiscard]] virtual const char *name() const noexcept = 0;

  /// False means this backend is not usable on this machine -- no
  /// permission on /dev/input, a framework that failed to load. The core
  /// drops it and carries on with the others, which is the whole reason
  /// initialisation is allowed to fail.
  virtual bool init(Host *host) = 0;
  virtual void shutdown() = 0;

  /// `rescan` is a hint that enough time has passed to look for new
  /// hardware. Backends with real hotplug notification ignore it.
  virtual void poll(bool rescan) = 0;

  virtual bool rumble(void *handle, float low, float high,
                      std::uint32_t duration_ms) {
    (void)handle;
    (void)low;
    (void)high;
    (void)duration_ms;
    return false;
  }
  virtual bool rumble_triggers(void *handle, float left, float right,
                               std::uint32_t duration_ms) {
    (void)handle;
    (void)left;
    (void)right;
    (void)duration_ms;
    return false;
  }
  virtual bool set_led(void *handle, std::uint8_t r, std::uint8_t g,
                       std::uint8_t b) {
    (void)handle;
    (void)r;
    (void)g;
    (void)b;
    return false;
  }
};

// Each backend that this build compiled defines its factory; the list of
// which ones those are is generated by CMake into gpplus_backends.inc.
// Backends are polled in the order they appear there, and a backend that
// is not in the list is not compiled at all -- there is no #ifdef inside
// any backend source, because a file that cannot build on this platform is
// simply not handed to the compiler.
#define GPPLUS_BACKEND(id) Backend *make_backend_##id();
#include "gpplus_backends.inc"
#undef GPPLUS_BACKEND

} // namespace gpp::detail

#endif // GPPLUS_BACKEND_HPP
