// Windows: DirectInput 8, for everything XInput cannot see.
//
// XInput's premise is that every device it reports is an Xbox-layout
// controller, which is also its limit: four slots, no device identity, and
// nothing that is not an Xbox pad. Arcade sticks, flight gear, racing
// wheels and every older pad are invisible to it. Those arrive here as a
// numbered pile of axes, buttons and hat switches, and the mapping
// database turns the pile back into a controller.
//
// DirectInput rather than Raw Input, although DirectInput has been
// deprecated for fifteen years. The database's `platform:Windows` lines
// were generated by SDL against DirectInput's enumeration order, and that
// order is the entire meaning of `a0` and `b3` in a mapping line. A Raw
// Input backend would need its own numbering and would match none of the
// ~870 Windows mappings, which is the only reason to have a raw backend at
// all.
//
// Compiled only where CMake found and probed dinput8; there is no #ifdef
// in this file.

#include "backend.hpp"
#include "mapping.hpp"

#include <algorithm>
#include <cctype>
#include <cstddef>
#include <cstdio>
#include <cstring>
#include <memory>
#include <string>
#include <vector>

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#define DIRECTINPUT_VERSION 0x0800
#include <dinput.h>
#include <windows.h>

namespace gpp::detail {
namespace {

/// One enumerated object, remembered by its offset into DIJOYSTATE2. The
/// offset is what decides its index: DIJOYSTATE2 lays out X, Y, Z, Rx, Ry,
/// Rz, Slider0, Slider1 in that order, so sorting by offset reproduces
/// SDL's axis numbering exactly. Anything cleverer renumbers the buttons
/// and silently breaks every mapping in the database.
///
/// For an axis the offset is *derived from what the axis is*, never taken
/// from the enumeration: see joystate_offset().
struct Object {
  DWORD offset = 0;
  int index = 0;
  LONG minimum = -32768;
  LONG maximum = 32767;
};

struct Entry {
  IDirectInputDevice8W *device = nullptr;
  int slot = -1;
  GUID instance{};
  std::vector<Object> axes;
  std::vector<Object> buttons;
  std::vector<Object> povs;
  /// Acquisition is lost whenever the desktop decides so -- a lock screen,
  /// a UAC prompt, another process going exclusive. Re-acquiring is
  /// routine and not an error, which is exactly why a lost acquisition
  /// must never be read as an unplug.
  bool acquired = false;
  /// Sliders seen so far; the n-th slider is DIJOYSTATE2's n-th.
  int sliders = 0;
  /// Set by each enumeration pass. A device that stops turning up in the
  /// enumeration is gone; that, and not an HRESULT, is how removal is
  /// detected -- DirectInput's error codes cannot tell "unplugged" from
  /// "the lock screen has the device" with any reliability.
  bool seen = true;
};

/// The window DirectInput insists on. gpplus exists so that a game does not
/// have to hand its window to an input library, and SetCooperativeLevel
/// refuses to work without one -- so the backend makes its own, a
/// message-only window that is never shown, never pumped and never seen.
/// This is the single place in the library that touches windowing; keep it
/// that way.
HWND create_message_window() {
  static const wchar_t *kClassName = L"gpplusDinputSink";
  WNDCLASSEXW wc = {};
  wc.cbSize = sizeof(wc);
  wc.lpfnWndProc = DefWindowProcW;
  wc.hInstance = GetModuleHandleW(nullptr);
  wc.lpszClassName = kClassName;
  // A class already registered is the normal case for a second Context;
  // anything else is fatal to this backend and nothing else.
  if (RegisterClassExW(&wc) == 0 &&
      GetLastError() != ERROR_CLASS_ALREADY_EXISTS) {
    return nullptr;
  }
  return CreateWindowExW(0, kClassName, L"gpplus", 0, 0, 0, 0, 0, HWND_MESSAGE,
                         nullptr, wc.hInstance, nullptr);
}

std::string to_utf8(const wchar_t *wide) {
  if (wide == nullptr || wide[0] == L'\0') {
    return {};
  }
  const int needed =
      WideCharToMultiByte(CP_UTF8, 0, wide, -1, nullptr, 0, nullptr, nullptr);
  if (needed <= 1) {
    return {};
  }
  std::string out(static_cast<std::size_t>(needed - 1), '\0');
  WideCharToMultiByte(CP_UTF8, 0, wide, -1, out.data(), needed, nullptr,
                      nullptr);
  return out;
}

/**
 * @brief Whether this device is an XInput pad wearing a DirectInput hat.
 *
 * Every XInput controller is also enumerated by DirectInput, so without
 * this check each Xbox pad is reported twice -- once mapped by XInput and
 * once as a nameless axis pile. The device interface path of an XInput
 * device contains "IG_"; that is how the platform marks them, it is what
 * SDL tests, and it costs one property query rather than the WMI walk the
 * official sample uses.
 */
bool is_xinput_device(IDirectInputDevice8W *device) {
  DIPROPGUIDANDPATH prop = {};
  prop.diph.dwSize = sizeof(prop);
  prop.diph.dwHeaderSize = sizeof(prop.diph);
  prop.diph.dwObj = 0;
  prop.diph.dwHow = DIPH_DEVICE;
  if (FAILED(device->GetProperty(DIPROP_GUIDANDPATH, &prop.diph))) {
    return false;
  }
  std::string path = to_utf8(prop.wszPath);
  std::transform(path.begin(), path.end(), path.begin(), [](unsigned char c) {
    return static_cast<char>(std::tolower(c));
  });
  return path.find("ig_") != std::string::npos;
}

/// DirectInput reports a POV in hundredths of a degree clockwise from up,
/// and a centred one as -1. The conversion itself is in mapping.cpp, where
/// it is portable and has tests -- this backend cannot be run by most of
/// the people who will change it.
std::uint8_t pov_mask(DWORD pov) {
  return hat_mask_from_centidegrees(static_cast<std::uint32_t>(pov));
}

float normalize(LONG value, LONG minimum, LONG maximum) {
  if (maximum <= minimum) {
    return 0.0f;
  }
  const double span = static_cast<double>(maximum) - minimum;
  const double t = (static_cast<double>(value) - minimum) / span;
  return static_cast<float>(t * 2.0 - 1.0);
}

/// Reads one axis out of DIJOYSTATE2 by its offset. The struct is a fixed
/// layout, so the offset the enumeration gave us indexes straight into it.
LONG axis_value(const DIJOYSTATE2 &state, DWORD offset) {
  LONG value = 0;
  std::memcpy(&value, reinterpret_cast<const char *>(&state) + offset,
              sizeof(value));
  return value;
}

class DinputBackend;

/// EnumDevices and EnumObjects are C callbacks with a void* for context;
/// these two trampolines are the whole of the glue.
BOOL CALLBACK enum_device_cb(const DIDEVICEINSTANCEW *instance, void *context);
BOOL CALLBACK enum_object_cb(const DIDEVICEOBJECTINSTANCEW *object,
                             void *context);

class DinputBackend final : public Backend {
public:
  const char *name() const noexcept override { return "dinput"; }

  bool init(Host *host) override {
    host_ = host;
    window_ = create_message_window();
    if (window_ == nullptr) {
      return false;
    }
    const HRESULT hr = DirectInput8Create(
        GetModuleHandleW(nullptr), DIRECTINPUT_VERSION, IID_IDirectInput8W,
        reinterpret_cast<void **>(&dinput_), nullptr);
    if (FAILED(hr) || dinput_ == nullptr) {
      // No DirectInput on this machine is not an error worth failing a
      // game over; XInput is very likely still there.
      DestroyWindow(window_);
      window_ = nullptr;
      return false;
    }
    return true;
  }

  void shutdown() override {
    for (auto &e : entries_) {
      release(*e);
    }
    entries_.clear();
    if (dinput_ != nullptr) {
      dinput_->Release();
      dinput_ = nullptr;
    }
    if (window_ != nullptr) {
      DestroyWindow(window_);
      window_ = nullptr;
    }
    host_ = nullptr;
  }

  void poll(bool rescan) override {
    if (rescan) {
      for (auto &e : entries_) {
        e->seen = false;
      }
      dinput_->EnumDevices(DI8DEVCLASS_GAMECTRL, enum_device_cb, this,
                           DIEDFL_ATTACHEDONLY);
      for (std::size_t i = entries_.size(); i-- > 0;) {
        if (!entries_[i]->seen) {
          Entry &e = *entries_[i];
          host_->remove_device(e.slot);
          release(e);
          entries_.erase(entries_.begin() + static_cast<long>(i));
        }
      }
    }
    for (auto &entry : entries_) {
      read(*entry);
    }
  }

  /// Called back from the enumeration trampoline.
  void consider(const DIDEVICEINSTANCEW *instance) {
    if (Entry *existing = find(instance->guidInstance)) {
      existing->seen = true;
      return;
    }
    IDirectInputDevice8W *device = nullptr;
    if (FAILED(
            dinput_->CreateDevice(instance->guidInstance, &device, nullptr)) ||
        device == nullptr) {
      return;
    }
    if (is_xinput_device(device)) {
      device->Release();
      return;
    }
    if (FAILED(device->SetDataFormat(&c_dfDIJoystick2))) {
      device->Release();
      return;
    }
    // Background and non-exclusive: a game that is not focused should stop
    // *acting* on input, which is its decision, not stop receiving it. And
    // exclusive access would take the device away from everything else on
    // the desktop, which is not a library's call to make.
    if (FAILED(device->SetCooperativeLevel(window_, DISCL_BACKGROUND |
                                                        DISCL_NONEXCLUSIVE))) {
      device->Release();
      return;
    }

    auto entry = std::make_unique<Entry>();
    entry->device = device;
    entry->instance = instance->guidInstance;
    device->EnumObjects(enum_object_cb, entry.get(),
                        DIDFT_ABSAXIS | DIDFT_POV | DIDFT_BUTTON);

    // Sorted by offset, then numbered. This *is* the compatibility with
    // the database; see the comment on Object.
    const auto by_offset = [](const Object &a, const Object &b) {
      return a.offset < b.offset;
    };
    std::sort(entry->axes.begin(), entry->axes.end(), by_offset);
    std::sort(entry->buttons.begin(), entry->buttons.end(), by_offset);
    std::sort(entry->povs.begin(), entry->povs.end(), by_offset);
    for (std::size_t i = 0; i < entry->axes.size(); ++i) {
      entry->axes[i].index = static_cast<int>(i);
    }
    for (std::size_t i = 0; i < entry->buttons.size(); ++i) {
      entry->buttons[i].index = static_cast<int>(i);
    }
    for (std::size_t i = 0; i < entry->povs.size(); ++i) {
      entry->povs[i].index = static_cast<int>(i);
    }

    if (entry->axes.empty() && entry->buttons.empty()) {
      device->Release();
      return;
    }

    DeviceDesc desc;
    desc.name = to_utf8(instance->tszProductName);
    if (desc.name.empty()) {
      desc.name = "DirectInput Controller";
    }
    DIPROPDWORD vidpid = {};
    vidpid.diph.dwSize = sizeof(vidpid);
    vidpid.diph.dwHeaderSize = sizeof(vidpid.diph);
    vidpid.diph.dwObj = 0;
    vidpid.diph.dwHow = DIPH_DEVICE;
    if (SUCCEEDED(device->GetProperty(DIPROP_VIDPID, &vidpid.diph))) {
      desc.vendor = static_cast<std::uint16_t>(LOWORD(vidpid.dwData));
      desc.product = static_cast<std::uint16_t>(HIWORD(vidpid.dwData));
    }
    // Version zero, always: SDL wrote the Windows lines that way, and a
    // guid that disagrees matches nothing.
    desc.guid = make_guid(0x03, desc.vendor, desc.product, 0, desc.name);
    desc.raw_axis_count = static_cast<int>(entry->axes.size());
    desc.raw_button_count = static_cast<int>(entry->buttons.size());
    desc.raw_hat_count = static_cast<int>(entry->povs.size());
    // Force feedback here is IDirectInputEffect and a second protocol, for
    // devices whose motors XInput already drives. Not attempted.
    desc.caps.rumble = false;
    desc.handle = entry.get();
    desc.unique_key = guid_key(instance->guidInstance);

    if (host_->hardware_claimed(desc.vendor, desc.product, desc.unique_key)) {
      device->Release();
      return;
    }
    const int slot = host_->add_device(desc);
    if (slot < 0) {
      device->Release();
      return;
    }
    entry->slot = slot;
    apply_axis_ranges(*entry);
    entries_.push_back(std::move(entry));
  }

  /// Where DIJOYSTATE2 keeps an axis, decided by what the axis *is*.
  ///
  /// The `dwOfs` that EnumObjects reports is not that: on a DualShock 4 it
  /// listed Rz at 0, Z at 4, Y at 8 and X at 12, with the buttons at 212 --
  /// the device's own layout, whatever data format was set. Read as
  /// DIJOYSTATE2 offsets those land on the right fields for the first four
  /// axes by coincidence and on the two sliders, which are always zero, for
  /// the last two, while the real data sits in Ry and Rz. So the axis is
  /// identified by its type GUID and placed where the format puts it, which
  /// is also how SDL does it.
  ///
  /// Returns false for an axis with no place in the format (an unknown type,
  /// or a third slider), which is left out rather than misread.
  static bool joystate_offset(const GUID &type, Entry &entry, DWORD &offset) {
    if (IsEqualGUID(type, GUID_XAxis)) {
      offset = offsetof(DIJOYSTATE2, lX);
    } else if (IsEqualGUID(type, GUID_YAxis)) {
      offset = offsetof(DIJOYSTATE2, lY);
    } else if (IsEqualGUID(type, GUID_ZAxis)) {
      offset = offsetof(DIJOYSTATE2, lZ);
    } else if (IsEqualGUID(type, GUID_RxAxis)) {
      offset = offsetof(DIJOYSTATE2, lRx);
    } else if (IsEqualGUID(type, GUID_RyAxis)) {
      offset = offsetof(DIJOYSTATE2, lRy);
    } else if (IsEqualGUID(type, GUID_RzAxis)) {
      offset = offsetof(DIJOYSTATE2, lRz);
    } else if (IsEqualGUID(type, GUID_Slider)) {
      constexpr int kSliders = 2;
      if (entry.sliders >= kSliders) {
        return false;
      }
      offset = static_cast<DWORD>(offsetof(DIJOYSTATE2, rglSlider) +
                                  sizeof(LONG) * entry.sliders);
      ++entry.sliders;
    } else {
      return false;
    }
    return true;
  }

  /// Called back from the object enumeration trampoline.
  static void collect(Entry &entry, const DIDEVICEOBJECTINSTANCEW *object) {
    Object item;
    item.offset = object->dwOfs;
    if ((object->dwType & DIDFT_ABSAXIS) != 0) {
      if (joystate_offset(object->guidType, entry, item.offset)) {
        entry.axes.push_back(item);
      }
    } else if ((object->dwType & DIDFT_POV) != 0) {
      entry.povs.push_back(item);
    } else if ((object->dwType & DIDFT_BUTTON) != 0) {
      entry.buttons.push_back(item);
    }
  }

private:
  Entry *find(const GUID &instance) {
    for (auto &e : entries_) {
      if (IsEqualGUID(e->instance, instance)) {
        return e.get();
      }
    }
    return nullptr;
  }

  static std::string guid_key(const GUID &guid) {
    char buffer[40] = {};
    std::snprintf(buffer, sizeof(buffer), "dinput:%08lx-%04x-%04x-%02x%02x",
                  static_cast<unsigned long>(guid.Data1), guid.Data2,
                  guid.Data3, guid.Data4[0], guid.Data4[1]);
    return buffer;
  }

  /// Ask for the full signed range with the hardware's own deadzone and
  /// saturation switched off, so that the shaping the core applies is the
  /// only shaping there is.
  void apply_axis_ranges(Entry &entry) {
    for (Object &axis : entry.axes) {
      DIPROPRANGE range = {};
      range.diph.dwSize = sizeof(range);
      range.diph.dwHeaderSize = sizeof(range.diph);
      range.diph.dwObj = axis.offset;
      range.diph.dwHow = DIPH_BYOFFSET;
      range.lMin = -32768;
      range.lMax = 32767;
      if (SUCCEEDED(entry.device->SetProperty(DIPROP_RANGE, &range.diph))) {
        axis.minimum = range.lMin;
        axis.maximum = range.lMax;
      } else if (SUCCEEDED(
                     entry.device->GetProperty(DIPROP_RANGE, &range.diph))) {
        // A device that will not be told still has to be read correctly.
        axis.minimum = range.lMin;
        axis.maximum = range.lMax;
      }

      DIPROPDWORD dword = {};
      dword.diph.dwSize = sizeof(dword);
      dword.diph.dwHeaderSize = sizeof(dword.diph);
      dword.diph.dwObj = axis.offset;
      dword.diph.dwHow = DIPH_BYOFFSET;
      dword.dwData = 0;
      entry.device->SetProperty(DIPROP_DEADZONE, &dword.diph);
      dword.dwData = 10000;
      entry.device->SetProperty(DIPROP_SATURATION, &dword.diph);
    }
  }

  /// Reads one device, or quietly does nothing if it is not readable this
  /// frame. Failure here is never removal: see Entry::seen.
  void read(Entry &entry) {
    if (!entry.acquired) {
      if (FAILED(entry.device->Acquire())) {
        return; // busy desktop, locked screen; try again next frame
      }
      entry.acquired = true;
    }

    DIJOYSTATE2 state = {};
    if (FAILED(entry.device->Poll())) {
      entry.acquired = false;
      return;
    }
    if (FAILED(entry.device->GetDeviceState(sizeof(state), &state))) {
      entry.acquired = false;
      return;
    }

    for (const Object &axis : entry.axes) {
      host_->set_raw_axis(entry.slot, axis.index,
                          normalize(axis_value(state, axis.offset),
                                    axis.minimum, axis.maximum));
    }
    for (const Object &button : entry.buttons) {
      const std::size_t i = static_cast<std::size_t>(button.index);
      if (i < sizeof(state.rgbButtons)) {
        host_->set_raw_button(entry.slot, button.index,
                              (state.rgbButtons[i] & 0x80) != 0);
      }
    }
    for (const Object &pov : entry.povs) {
      const std::size_t i = static_cast<std::size_t>(pov.index);
      if (i < sizeof(state.rgdwPOV) / sizeof(state.rgdwPOV[0])) {
        host_->set_raw_hat(entry.slot, pov.index, pov_mask(state.rgdwPOV[i]));
      }
    }
  }

  static void release(Entry &entry) {
    if (entry.device != nullptr) {
      entry.device->Unacquire();
      entry.device->Release();
      entry.device = nullptr;
    }
  }

  Host *host_ = nullptr;
  IDirectInput8W *dinput_ = nullptr;
  HWND window_ = nullptr;
  std::vector<std::unique_ptr<Entry>> entries_;
};

BOOL CALLBACK enum_device_cb(const DIDEVICEINSTANCEW *instance, void *context) {
  static_cast<DinputBackend *>(context)->consider(instance);
  return DIENUM_CONTINUE;
}

BOOL CALLBACK enum_object_cb(const DIDEVICEOBJECTINSTANCEW *object,
                             void *context) {
  DinputBackend::collect(*static_cast<Entry *>(context), object);
  return DIENUM_CONTINUE;
}

} // namespace

Backend *make_backend_dinput() { return new DinputBackend(); }

} // namespace gpp::detail
