# The controller mapping database, compiled in.
#
# The database is SDL_GameControllerDB: a decade of people plugging in a
# pad, working out which numbered button is which, and writing a line about
# it. It is data under the zlib license, so a project can carry it without
# carrying SDL -- which is the whole argument for this library existing.
#
# Three ways to get it, in order:
#   1. GPPLUS_CONTROLLER_DB_FILE, a path you supply.
#   2. A configure-time download (on by default; fails soft).
#   3. data/gamecontrollerdb.txt vendored next to this source tree.
# Then, on top of whichever of those was found, every data/contrib/*.txt:
# mappings recorded by people who own a pad the database lacks (see
# data/contrib/README.md). They go last, and a later line for the same guid
# replaces an earlier one, so a contributed fix wins over the entry it fixes.
# GPPLUS_BUNDLE_CONTROLLER_DB=OFF leaves them out along with everything else.
#
# If all of that comes up empty the build still succeeds and the library ships
# with no mappings: backends that report their own layout (GameController,
# XInput) are unaffected, and raw devices report as unmapped rather than
# wrong.
#
# What gets compiled in is only the lines for *this* platform, because a
# macOS binary has no use for 869 Windows mappings. That turns 600 KB into
# about 90.

set(_GPPLUS_DB_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}")

set(GPPLUS_CONTROLLER_DB_URL
    "https://raw.githubusercontent.com/mdqinc/SDL_GameControllerDB/master/gamecontrollerdb.txt"
    CACHE STRING "Where to fetch the controller mapping database from")
set(GPPLUS_CONTROLLER_DB_SHA256 "" CACHE STRING
    "Expected SHA256 of the downloaded database. Empty accepts whatever \
arrives, which is fine for a data file whose worst failure is an unmapped \
pad; set it if your build has to be bit-reproducible.")

function(_gpplus_db_platform_tag out_var)
  if(APPLE)
    if(CMAKE_SYSTEM_NAME STREQUAL "iOS")
      set(${out_var} "iOS" PARENT_SCOPE)
    else()
      set(${out_var} "Mac OS X" PARENT_SCOPE)
    endif()
  elseif(WIN32)
    set(${out_var} "Windows" PARENT_SCOPE)
  elseif(ANDROID)
    set(${out_var} "Android" PARENT_SCOPE)
  else()
    set(${out_var} "Linux" PARENT_SCOPE)
  endif()
endfunction()

# Writes `out_cpp`: a translation unit defining gpp::builtin_controller_db().
#
# `db_files` is a list, in load order. The text goes in as a byte array
# rather than a string literal on purpose. MSVC caps a string literal at
# 16 KB and concatenated literals at 64 KB, so the obvious encoding builds
# everywhere except the compiler most likely to be pointed at a game.
function(_gpplus_write_db_source db_files platform_tag out_cpp)
  set(kept 0)
  set(body "")
  set(chunks "")

  foreach(db_file IN LISTS db_files)
    if(NOT EXISTS "${db_file}")
      continue()
    endif()
    file(STRINGS "${db_file}" lines ENCODING UTF-8)
    foreach(line IN LISTS lines)
      if(line MATCHES "^[ \t]*#" OR line STREQUAL "")
        continue()
      endif()
      # A line with no platform field applies everywhere; one with another
      # platform's tag is dead weight in this binary.
      if(line MATCHES "platform:" AND NOT line MATCHES "platform:${platform_tag}[,]?")
        continue()
      endif()
      string(HEX "${line}" hex)
      string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
      string(APPEND body "${bytes}0x0a,\n")
      math(EXPR kept "${kept} + 1")
      # Flushed periodically: CMake string append is quadratic enough to
      # notice on a file this size.
      string(LENGTH "${body}" body_len)
      if(body_len GREATER 200000)
        list(APPEND chunks "${body}")
        set(body "")
      endif()
    endforeach()
  endforeach()
  list(APPEND chunks "${body}")
  string(JOIN "" all_bytes ${chunks})

  set(header "// Generated by cmake/GpplusControllerDB.cmake. Do not edit.
//
// Mapping data from SDL_GameControllerDB (zlib license); see LICENSE.
// Source: ${GPPLUS_CONTROLLER_DB_URL}
// Filtered to platform: ${platform_tag} (${kept} mappings)

namespace gpp {

")
  if(kept EQUAL 0)
    string(APPEND header "const char *builtin_controller_db() noexcept { return \"\"; }

} // namespace gpp
")
    file(WRITE "${out_cpp}" "${header}")
  else()
    file(WRITE "${out_cpp}" "${header}static const char kDb[] = {
${all_bytes}0x00};

const char *builtin_controller_db() noexcept { return kDb; }

} // namespace gpp
")
  endif()
  set(GPPLUS_CONTROLLER_DB_ENTRIES "${kept}" PARENT_SCOPE)
endfunction()

function(gpplus_prepare_controller_db out_source)
  _gpplus_db_platform_tag(platform_tag)
  set(db_file "")
  set(bundled FALSE)

  if(GPPLUS_CONTROLLER_DB_FILE)
    if(NOT EXISTS "${GPPLUS_CONTROLLER_DB_FILE}")
      message(FATAL_ERROR
        "GPPLUS_CONTROLLER_DB_FILE=${GPPLUS_CONTROLLER_DB_FILE} does not exist")
    endif()
    set(db_file "${GPPLUS_CONTROLLER_DB_FILE}")
    set(bundled TRUE)
  elseif(GPPLUS_BUNDLE_CONTROLLER_DB)
    set(bundled TRUE)
    set(cached "${CMAKE_CURRENT_BINARY_DIR}/gamecontrollerdb.txt")
    set(vendored "${_GPPLUS_DB_MODULE_DIR}/../data/gamecontrollerdb.txt")
    if(GPPLUS_DOWNLOAD_CONTROLLER_DB AND NOT EXISTS "${cached}")
      message(STATUS "gpplus: downloading controller database")
      set(hash_args "")
      if(GPPLUS_CONTROLLER_DB_SHA256)
        set(hash_args EXPECTED_HASH "SHA256=${GPPLUS_CONTROLLER_DB_SHA256}")
      endif()
      file(DOWNLOAD "${GPPLUS_CONTROLLER_DB_URL}" "${cached}"
           INACTIVITY_TIMEOUT 15 TIMEOUT 60 STATUS status ${hash_args})
      list(GET status 0 code)
      if(NOT code EQUAL 0)
        list(GET status 1 reason)
        # Soft failure by design: an offline build, a CI box with no egress
        # or a corporate proxy must not stop a game from compiling over a
        # data file.
        message(WARNING "gpplus: could not download the controller database "
                        "(${reason}); falling back")
        file(REMOVE "${cached}")
      endif()
    endif()
    if(EXISTS "${cached}")
      set(db_file "${cached}")
    elseif(EXISTS "${vendored}")
      set(db_file "${vendored}")
    else()
      message(WARNING
        "gpplus: no controller database available. Raw devices (evdev, "
        "IOKit HID) will report as unmapped. Set GPPLUS_CONTROLLER_DB_FILE, "
        "enable GPPLUS_DOWNLOAD_CONTROLLER_DB, or drop the file in data/.")
    endif()
  endif()

  set(db_files "")
  if(db_file)
    list(APPEND db_files "${db_file}")
  endif()

  # CONFIGURE_DEPENDS re-globs at build time, so a new file dropped into
  # data/contrib/ triggers a reconfigure by itself; editing one that is
  # already there is covered by the property below.
  set(contrib_files "")
  if(bundled)
    file(GLOB contrib_files CONFIGURE_DEPENDS
         "${_GPPLUS_DB_MODULE_DIR}/../data/contrib/*.txt")
    list(SORT contrib_files)
    foreach(f IN LISTS contrib_files)
      set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${f}")
    endforeach()
    list(APPEND db_files ${contrib_files})
  endif()

  set(generated "${CMAKE_CURRENT_BINARY_DIR}/gpplus_controller_db.cpp")
  _gpplus_write_db_source("${db_files}" "${platform_tag}" "${generated}")
  if(db_files)
    list(LENGTH contrib_files n_contrib)
    message(STATUS
      "gpplus: ${GPPLUS_CONTROLLER_DB_ENTRIES} mappings for '${platform_tag}' "
      "from ${db_file} + ${n_contrib} contrib file(s)")
  endif()
  set(${out_source} "${generated}" PARENT_SCOPE)
  set(GPPLUS_CONTROLLER_DB_ENTRIES "${GPPLUS_CONTROLLER_DB_ENTRIES}" PARENT_SCOPE)
endfunction()
